# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import user_feedback_pb2 as user__feedback__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_feedback_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeedbackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitFeedback = channel.unary_unary(
                '/FeedbackService/SubmitFeedback',
                request_serializer=user__feedback__pb2.SubmitFeedbackRequest.SerializeToString,
                response_deserializer=user__feedback__pb2.SubmitFeedbackResponse.FromString,
                _registered_method=True)
        self.GetDrugFeedback = channel.unary_unary(
                '/FeedbackService/GetDrugFeedback',
                request_serializer=user__feedback__pb2.DrugFeedbackRequest.SerializeToString,
                response_deserializer=user__feedback__pb2.DrugFeedbackResponse.FromString,
                _registered_method=True)
        self.GetUserFeedbacks = channel.unary_unary(
                '/FeedbackService/GetUserFeedbacks',
                request_serializer=user__feedback__pb2.UserFeedbackRequest.SerializeToString,
                response_deserializer=user__feedback__pb2.DrugFeedbackResponse.FromString,
                _registered_method=True)
        self.DeleteUserFeedbacks = channel.unary_unary(
                '/FeedbackService/DeleteUserFeedbacks',
                request_serializer=user__feedback__pb2.UserFeedbackRequest.SerializeToString,
                response_deserializer=user__feedback__pb2.Response.FromString,
                _registered_method=True)
        self.UpdateFeedback = channel.unary_unary(
                '/FeedbackService/UpdateFeedback',
                request_serializer=user__feedback__pb2.UpdateFeedbackRequest.SerializeToString,
                response_deserializer=user__feedback__pb2.Response.FromString,
                _registered_method=True)
        self.DeleteFeedback = channel.unary_unary(
                '/FeedbackService/DeleteFeedback',
                request_serializer=user__feedback__pb2.DeleteFeedbackRequest.SerializeToString,
                response_deserializer=user__feedback__pb2.Response.FromString,
                _registered_method=True)
        self.ListAllFeedbacks = channel.unary_unary(
                '/FeedbackService/ListAllFeedbacks',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=user__feedback__pb2.ListAllFeedbacksResponse.FromString,
                _registered_method=True)


class FeedbackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDrugFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserFeedbacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserFeedbacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllFeedbacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFeedback,
                    request_deserializer=user__feedback__pb2.SubmitFeedbackRequest.FromString,
                    response_serializer=user__feedback__pb2.SubmitFeedbackResponse.SerializeToString,
            ),
            'GetDrugFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDrugFeedback,
                    request_deserializer=user__feedback__pb2.DrugFeedbackRequest.FromString,
                    response_serializer=user__feedback__pb2.DrugFeedbackResponse.SerializeToString,
            ),
            'GetUserFeedbacks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFeedbacks,
                    request_deserializer=user__feedback__pb2.UserFeedbackRequest.FromString,
                    response_serializer=user__feedback__pb2.DrugFeedbackResponse.SerializeToString,
            ),
            'DeleteUserFeedbacks': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserFeedbacks,
                    request_deserializer=user__feedback__pb2.UserFeedbackRequest.FromString,
                    response_serializer=user__feedback__pb2.Response.SerializeToString,
            ),
            'UpdateFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFeedback,
                    request_deserializer=user__feedback__pb2.UpdateFeedbackRequest.FromString,
                    response_serializer=user__feedback__pb2.Response.SerializeToString,
            ),
            'DeleteFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFeedback,
                    request_deserializer=user__feedback__pb2.DeleteFeedbackRequest.FromString,
                    response_serializer=user__feedback__pb2.Response.SerializeToString,
            ),
            'ListAllFeedbacks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllFeedbacks,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=user__feedback__pb2.ListAllFeedbacksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FeedbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FeedbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeedbackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedbackService/SubmitFeedback',
            user__feedback__pb2.SubmitFeedbackRequest.SerializeToString,
            user__feedback__pb2.SubmitFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDrugFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedbackService/GetDrugFeedback',
            user__feedback__pb2.DrugFeedbackRequest.SerializeToString,
            user__feedback__pb2.DrugFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserFeedbacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedbackService/GetUserFeedbacks',
            user__feedback__pb2.UserFeedbackRequest.SerializeToString,
            user__feedback__pb2.DrugFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserFeedbacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedbackService/DeleteUserFeedbacks',
            user__feedback__pb2.UserFeedbackRequest.SerializeToString,
            user__feedback__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedbackService/UpdateFeedback',
            user__feedback__pb2.UpdateFeedbackRequest.SerializeToString,
            user__feedback__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedbackService/DeleteFeedback',
            user__feedback__pb2.DeleteFeedbackRequest.SerializeToString,
            user__feedback__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllFeedbacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FeedbackService/ListAllFeedbacks',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            user__feedback__pb2.ListAllFeedbacksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
