apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-feedback-service
  labels:  
    app: user-feedback-service
spec:
  replicas: 1
  strategy:  
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Número máximo de pods indisponíveis durante o update
      maxSurge: 1  # Número máximo de pods extras durante a atualização
  selector:  
    matchLabels:
      app: user-feedback-service
  template:
    metadata:
      labels:  
        app: user-feedback-service
    spec:
      containers:
      - name: user-feedback
        image: anardsm/user-feedback-service:latest
        ports:
        - containerPort: 50053
        env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: DB_URL
        resources:
          requests:
            cpu: "100m"      
            memory: "128Mi"  
          limits:
            cpu: "200m"      
            memory: "256Mi"  

        livenessProbe:
          grpc:
            port: 50053
            service: "feedback.FeedbackService"
          initialDelaySeconds: 45  
          periodSeconds: 20
          failureThreshold: 3

        readinessProbe:
          tcpSocket:
            port: 50053  
          initialDelaySeconds: 30 
          periodSeconds: 10 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Número máximo de pods indisponíveis durante o update
      maxSurge: 1  # Número máximo de pods extras durante a atualização
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: anardsm/user-service:latest
        ports:
        - containerPort: 50051 
        env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: DB_URL
        resources:
          requests:
            cpu: "100m"       
            memory: "128Mi"   
          limits:
            cpu: "200m"       
            memory: "256Mi"  

        livenessProbe:
          grpc:
            port: 50051
            service: "user.UserService"
          initialDelaySeconds: 15  
          periodSeconds: 10  

        readinessProbe:
          tcpSocket:
            port: 50051  
          initialDelaySeconds: 15 
          periodSeconds: 10 

