FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. user.proto

EXPOSE 50051

ENTRYPOINT ["python", "user_server.py"]

