# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"9\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x0cUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"*\n\x13RegisterUserRequest\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"N\n\x11UpdateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tnew_email\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\"%\n\x11\x44\x65leteUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"9\n\x15UserOperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf1\x01\n\x0bUserService\x12<\n\x0cRegisterUser\x12\x14.RegisterUserRequest\x1a\x16.UserOperationResponse\x12\x38\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x16.UserOperationResponse\x12\x38\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x16.UserOperationResponse\x12\x30\n\x0bGetUserInfo\x12\x12.DeleteUserRequest\x1a\r.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=14
  _globals['_USER']._serialized_end=71
  _globals['_USERRESPONSE']._serialized_start=73
  _globals['_USERRESPONSE']._serialized_end=120
  _globals['_REGISTERUSERREQUEST']._serialized_start=122
  _globals['_REGISTERUSERREQUEST']._serialized_end=164
  _globals['_UPDATEUSERREQUEST']._serialized_start=166
  _globals['_UPDATEUSERREQUEST']._serialized_end=244
  _globals['_DELETEUSERREQUEST']._serialized_start=246
  _globals['_DELETEUSERREQUEST']._serialized_end=283
  _globals['_USEROPERATIONRESPONSE']._serialized_start=285
  _globals['_USEROPERATIONRESPONSE']._serialized_end=342
  _globals['_USERSERVICE']._serialized_start=345
  _globals['_USERSERVICE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
